networks:
  my_network:
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - my_network
    restart: always
    volumes:
      - ./app:/app
      - /app/node_modules

  landing-page:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - my_network
    restart: always
    volumes:
      - ./landing-page:/landing-page

  # cron_delete_rubbish:
  #   image: alpine
  #   volumes:
  #     - ./app/scripts:/scripts
  #   networks:
  #     - my_network
  #   working_dir: /scripts
  #   command: "crond -f -d 8"
  #
  #   # Define the cron job to run the script every Sunday at midnight (0 0 * * 0)
  #   environment:
  #     - 'CRON_SCHEDULE=0 0 * * 0'
  #     - 'CRON_COMMAND=node /scripts/deleteRubbish.js'
  #   restart: always


  cron_backup:
    build:
      context: ./app
      dockerfile: Dockerfile-cron
    volumes:
      - ./app/backups:/backups
    env_file:
      - ./app/.env
    networks:
      - my_network
    working_dir: /backups
    restart: always

