version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  landing-page:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Use a different host port for the second app
    restart: always
