version: '3.8'

networks:
  my_network: # Define the custom network
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - my_network # Connect the "app" service to the custom network
    restart: always

  landing-page:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - my_network # Connect the "landing-page" service to the custom network
    restart: always
