FROM alpine:latest

# Install MongoDB tools
RUN apk add --no-cache mongodb-tools bash curl aws-cli

# Set working directory
WORKDIR /backups

# Copy the existing scripts into the container
COPY ./backups /backups

# Make sure the script is executable
RUN chmod +x /backups/create_mongo_dump.sh

# Ensure no existing cron jobs are running
RUN pkill cron || true

# Create logs dir
RUN mkdir -p /backups/logs

# Add the cron job
RUN (crontab -l ; echo "0 0 * * * /backups/create_mongo_dump.sh >> /backups/logs/backup.log 2>&1") | crontab -
#
# Start cron in the foreground (so the container stays running)
CMD ["crond", "-f", "-l", "2"]
