name: Build and Deploy App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Existing App Directory
        run: |
          rm -rf ./parent-folder/app

      - name: Clone App Repository
        run: |
          git clone git@github.com:Inventari-App/app.git ./parent-folder/app

      - name: Build and Deploy App
        env:
          DOCKER_BUILD_CONTEXT: ./parent-folder/app
          DOCKERFILE_PATH: ./parent-folder/app/Dockerfile
          APP_NAME: app
          HOST: ${{ secrets.HOST }}
          SSHKEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          docker-compose -f ./parent-folder/docker-compose.yml build $APP_NAME
          docker-compose -f ./parent-folder/docker-compose.yml up -d $APP_NAME
