name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSHKEY}}
          username: ${{secrets.USERNAME}}

          script: |
            if [ -d "$HOME/inventari-insti" ]; then
              cd $HOME/inventari-insti
              git checkout master
              git pull
            else
              git clone git@github.com:Inventari-App/inventari-insti.git
              cd $HOME/inventari-insti
            fi
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml build
            docker compose -f docker-compose.yml up -d