name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSHKEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          username: ${{secrets.USERNAME}}

          script: |
            git clone git@github.com:Inventari-App/inventari-insti.git
            cd inventari-insti
            docker build -t inventari-insti .
            docker stop inventari-insti
            docker rm inventari-insti
            docker run -d --restart unless-stopped -p 8080:3000 inventari-insti