name: Build and Deploy Landing Page

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Landing Page Repository
        run: |
          git clone git@github.com:Inventari-App/landing-page.git ./landing-page

      - name: Build and Deploy Landing Page
        env:
          DOCKER_BUILD_CONTEXT: ./landing-page
          DOCKERFILE_PATH: ./landing-page/Dockerfile
          APP_NAME: landing-page
          HOST: ${{ secrets.HOST }}
          SSHKEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          docker-compose -f ./docker-compose.yml build $APP_NAME
          docker-compose -f ./docker-compose.yml up -d $APP_NAME
